_wandb:
    value:
        cli_version: 0.22.3
        e:
            blhlplfbtejqi6dp14yf2wpd401uup34:
                codePath: GANS\DCGANS\mnsit_dcgans.py
                codePathLocal: mnsit_dcgans.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "509722226688"
                        used: "251375550464"
                email: ksprague0592@gmail.com
                executable: C:\Users\phoen\anaconda3\envs\ML\python.exe
                git:
                    commit: 60de5b21ca51afb35fdd11bf22013fd5d7963d2b
                    remote: https://github.com/UmbraServus/atlas-machine_learning.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-8df16a4c-ac2e-13b5-1b02-208afb823f48
                host: RegnumUmbra
                memory:
                    total: "16309932032"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\phoen\Atlas\atlas-machine_learning\GANS\DCGANS\mnsit_dcgans.py
                python: CPython 3.10.15
                root: C:\Users\phoen\Atlas\atlas-machine_learning\GANS\DCGANS
                startedAt: "2025-10-29T04:27:38.569667Z"
                writerId: blhlplfbtejqi6dp14yf2wpd401uup34
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.10.15
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
architecture:
    value: Baseline DCGAN
batch_size:
    value: 128
dataset:
    value: MNIST
framework:
    value: PyTorch
latent_dim:
    value: 100
learning_rate:
    value: 0.0002
model:
    value: DCGAN
num_epochs:
    value: 50
